version: '2'
services:
# Responsible to build dev/prod images 
  compiler-api:
    container_name: compiler-api
    image: golang:1.9.1
    volumes:
      - $PWD/:/go/src/github.com/mageddo/react-seo
      - $PWD/builder:/bin/builder
    working_dir: /go/src/github.com/mageddo/react-seo
    container_name: compiler-api
    command: builder build-api
    network_mode: bridge

  compiler-app:
    container_name: compiler-app
    image: node:8.7.0
    command: builder build-app
    volumes:
      - $PWD/:/app
      - $PWD/builder:/bin/builder
    working_dir: /app
    network_mode: bridge

  build: 
    container_name: build
    build:
      context: .
    image: defreitas/react-seo:1.0
    network_mode: bridge

# Responsible to run images in development environment
  react-seo-api:
    extends: compiler-api
    container_name: react-seo-api
    command: tail -f /dev/null
    hostname: api.react-seo.dev

  react-seo-app:
    extends: compiler-app
    container_name: react-seo-app
    hostname: app.react-seo.dev
    command: tail -f /dev/null

  react-seo-reverse-proxy:
    container_name: react-seo-reverse-proxy
    image: nginx:1.10
    ports:
      - 80:80
      - 443:443
    hostname: nginx.mageddo
    environment:
      - HOSTNAMES=react-seo.herokuapp.com
    entrypoint: /app/entrypoint.sh
    volumes:
      - ./nginx:/app
      - ./nginx/sites-enabled/:/etc/nginx/conf.d
    network_mode: bridge